#! /bin/bash

docker-compose -f ./application/docker-compose.yaml down
docker-compose -f ./postrges-database/docker-compose.db.yaml down
docker-compose -f ./postrges-database/docker-compose.migrations.yaml down
