version: '3.8'
services:
  identix-wallets-migrations:
    container_name: 'identix-wallets-migrations'
    image: 'identix-wallets'
    networks:
      - app-local-net
    volumes:
      - ../../.env:/usr/src/app/.env
    command: [ "yarn", "typeorm:run" ]

  identix-wallets-api:
    container_name: 'identix-wallets'
    depends_on:
      - identix-wallets-migrations
    image: 'identix-wallets'
    hostname: identix-wallets
    networks:
      - app-local-net
    volumes:
      - ../../.env:/usr/src/app/.env
    environment:
      - HTTP_PORT=3000
    ports:
      - "9000:3000"
    command: [ "yarn", "start" ]


networks:
  app-local-net:
    external: false
    driver: bridge
    name: app-local-net:qq
